export const en = {
	user: "User",
	firstName: "First name",
	lastName: "Last name",
	registrationDate: "Registration date",
	lastSeenDate: "Last seen date",
	isOnline: "is online",
	wasOnline: "was online",
	justNow: "just now",
	lessThanMinuteAgo: "less than a minute ago",
	coupleOfMinutesAgo: "couple of minutes ago",
	hourAgo: "hour ago",
	today: "today",
	yesterday: "yesterday",
	thisWeek: "this week",
	longTimeAgo: "long time ago",
};

export const ua = {
	user: "Користувач",
	firstName: "Ім'я",
	lastName: "Прізвище",
	registrationDate: "Дата реєстрації",
	lastSeenDate: "Останній раз в мережі",
	isOnline: "в мережі",
	wasOnline: "був в мережі",
	justNow: "щойно",
	lessThanMinuteAgo: "менше хвилини назад",
	coupleOfMinutesAgo: "декілька хвилин назад",
	hourAgo: "годину назад",
	today: "сьогодні",
	yesterday: "вчора",
	thisWeek: "на цьому тижні",
	longTimeAgo: "давно",
};
